name: CI

on:
  workflow_dispatch: {}        # <-- запуск вручную из Actions
  pull_request:
    branches: [main]           # PR в main
  push:
    branches: [main]           # пуши в main (если разрешены)

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci --no-audit --no-fund; else npm i --no-audit --no-fund; fi

      # Юнит-тесты (если тестов нет — не падаем)
      - name: Test
        run: npm run test -- --passWithNoTests

      # Сборка (гарантирует, что билд вообще собирается)
      - name: Build
        run: npm run build

      # Лёгкий smoke-тест артефакта
      - name: Smoke check dist
        run: |
          test -f dist/index.html
          grep -q '<div id="root">' dist/index.html || (echo "no #root in index.html" && exit 1)
          test -f dist/404.html || cp dist/index.html dist/404.html

      # Сохраняем билд как артефакт PR (чтобы при желании скачать и посмотреть)
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
