jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      # ✅ Добавляем проверку перед билдом
      - name: List public before build
        run: |
          echo "=== PUBLIC ==="
          ls -lah public || true
          echo "=== find hero.mp4 ==="
          find public -name "hero.mp4" -print || true

      - name: Build
        run: npm run build

      # ✅ Добавляем проверку после билда
      - name: List dist after build
        run: |
          echo "=== DIST ==="
          ls -lah dist || true
          echo "=== find hero.mp4 in dist ==="
          find dist -name "hero.mp4" -print || true
